services:
    redis:
        image: bitnami/redis
        container_name: redis
        environment:
            REDIS_PASSWORD: redis
        network_mode: host
        volumes:
            - redis:/data

    minio:
        image: bitnami/minio
        container_name: minio
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_DEFAULT_BUCKETS: default
        network_mode: host
        volumes:
            - minio:/bitnami/minio/data


volumes:
    redis:
    minio: